name: NoChickenCombat
main: de.themoep.NoChickenCombat.NoChickenCombat
version: 0.1.1
description: Plugin against combat loggers
authors: [Phoenix616]
commands:
   NoChickenCombat:
      aliases: [ncc]
      description: Main plugin command.
      usage: /<command>
      permission: nochickencombat.admin
      permission-message: You don't have the permission <permission>
permissions:
   nochickencombat.admin:
      description: Gives permission to the admin command
      default: op
   nochickencombat.exempt:
      description: Exempts the player from the anti loggout kill
      default: op